config/routes.rb
Rails.application.routes.draw do
  resources :courses

  resources :notifications

  resources :workstatuses

  get 'admin'=>'admin#index'
  get 'admin/query'=>"admin#querybuild"
  post 'admin/getresults'=>"admin#getresults"
  get 'admin/createuser'=>"admin#rollno",:as=>"multi_user"
  post 'admin/createuser'
  get 'admin/excelsheet'=>"admin#excelsheet",:as=>"excel_user"
  post 'admin/userexcel'
  get 'college_profile/branch/:degree'=>"college_profiles#getdegree"
  get 'feedback'=>"home#feedback"
  get 'excelsheet'=>"college_profiles#excel_dump"
  post 'feedback/send'=>"home#send_feedback",:as=>"send_feedback"
  get 'admin/singleuser'=>"admin#singleuser",:as=>"single_user"
  post 'admin/singleuser'=>"admin#loneuser"
  get 'admin/changepassword'=>"admin#change_pass",:as=>"changepassword"
  post 'admin/changepassword'=>'admin#password',:as=>'password_path'
  get 'admin/edit_enable'=>"admin#enable_edit",:as=>"enable_edit"
  post 'admin/edit_enable'=>"admin#enable_edit_action",:as=>"enable"
  get 'myresume'=>"home#print",:as=>"myresume"
  get 'barcode/:filename.:extension'=>"application#barcode",:as=>"barcode"

  resources :companies

  resources :projects

  resources :extra_activities

  resources :semester_marks

  resources :academic_details

  resources :personal_profiles
  resources :college_profiles
  root 'home#index'
  get 'resume'=>"home#resume",:as=>"resume"
  get 'resume/submit'=>"home#submit",:as=>"submit_resume"
  get 'faq'=>"home#faq",:as=>"faq"
  get 'data/user/pic/:id/:filename.:extension'=>"application#download"
  get 'excelsheet/:filename.:extension'=>"application#exceldownload"
  get 'resume/complete'=>"home#complete",:as=>"complete"
  devise_for :users,:controllers=>{registrations:"registrations"},path_names: { sign_up: ''  }

end

app/models/academic_detail.rb
class AcademicDetail < ActiveRecord::Base
  belongs_to :user
  self.table_name="academic_detail"
  validates_presence_of :sslc_institute
  validates_presence_of :sslc_authority
  validates_presence_of :sslc_year
  validates_numericality_of :sslc_year
  validates_presence_of :hsc_mark
  validates_numericality_of :hsc_mark
  validates_presence_of :hsc_institute
  validates_presence_of :hsc_authority
  validates_presence_of :hsc_year
  validates_numericality_of :hsc_year
  validates_presence_of :ug_mark
  validates_numericality_of :ug_mark
  validates_presence_of :ug_institute
  validates_presence_of :ug_authority
  validates_presence_of :ug_year
  validates_numericality_of :ug_year
  validates_presence_of :pg_mark
  validates_numericality_of :pg_mark
  validates_presence_of :pg_institute
  validates_presence_of :pg_authority
  validates_presence_of :pg_year
  validates_numericality_of :pg_year
  validates_presence_of :pg_mark
  validates_numericality_of :pg_mark

end

app/models/college_profile.rb
class CollegeProfile < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id ,:message=>"already has a profile"
  validates_presence_of :level
  validates_numericality_of :semester,:on=>[:create,:update],:only_integer=>true
  validates_numericality_of :cgpa,:on=>[:create,:update]
  validates_presence_of :degree
  validates_presence_of :semester
  validates_presence_of :college
  validates_presence_of :cgpa
  validates_presence_of :current
  validates_presence_of :history
  validates :current,:numericality => { :greater_than_or_equal_to => 0 }
  validates :history,:numericality => { :greater_than_or_equal_to => 0 }
end

app/models/company.rb
class Company < ActiveRecord::Base
  extend SimpleCalendar
  has_calendar
end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/extra_activity.rb
class ExtraActivity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :area_of_interest
  validates_presence_of :extra_curricular
  validates_presence_of :hobby
  validates_presence_of :responsibilty
  validates_presence_of :electives
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/personal_profile.rb
class PersonalProfile < ActiveRecord::Base
  validates_presence_of :gender
  validates_presence_of :dob
  validates :dob,:date=>true
  validates_presence_of :age
  validates_numericality_of :age,:on=>[:create,:update]
  validates_presence_of :height
  validates_numericality_of :height,:on=>[:create,:update]
  validates_presence_of :weight
  validates_numericality_of :weight,:on=>[:create,:update]
  validates_presence_of :guardian_name
  validates_presence_of :guardian_occupation
  validates_presence_of :nationality
  validates_presence_of :mother_tongue
  validates_presence_of :language_speak
  validates_presence_of :language_write
  validates_presence_of :language_read
  validates_presence_of :social_status
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title
  validates_presence_of :desc
  validates_presence_of :technology
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/semester_mark.rb
class SemesterMark < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :semester
  validates_numericality_of :semester
  validates_presence_of :gpa
  validates_numericality_of :gpa
  validates_presence_of :pass_year
  validates_numericality_of :pass_year
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :pic,AvatarUploader
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable  
  validates_uniqueness_of :registerno
  validates_numericality_of :registerno
  has_one :college_profile
  has_one :personal_profile
  has_one :academic_detail
  has_many :semester_mark
  has_one :extra_activity
  has_many :project
  def email_required?
    false
  end
  def email_changed?
    false
  end
  def has_personal_profile(user)
    if not user.personal_profile.nil?
      return true
    end
    return false
  end
  def has_college_profile(user)
    if not user.college_profile.nil?
      return true
    end
    return false
  end
  def has_academic_detail(user)
    if not user.academic_detail.size==0
      return true
    end
    return false
  end
  def has_extra_activity(user)
    if not user.extra_activity.nil?
      return true
    end
    return false
  end

end

app/models/workstatus.rb
class Workstatus < ActiveRecord::Base
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def prev_month_link
    ->(param, date_range) { link_to(raw("&laquo;"), {param => date_range.first - 1.day},:class=>"cal-link") }
  end
  def next_month_link
    ->(param, date_range) { link_to(raw("&raquo;"), {param => date_range.last + 1.day})}
  end
  def splitter(string)
    return string.split(",")
  end
  def redder(value)
    if value.blank?  || value.nil? 
      "<p class='danger'>Nil</p>".html_safe
    elsif value==0.0 || value==0 || value=="0.0" || value=="0"
      "<p>Not applicable to me</p>".html_safe
    else
      "#{h value}".html_safe 
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/workstatuses_helper.rb
module WorkstatusesHelper
end

app/views/admin/change_pass.html.erb
<div class="well col-lg-6">
  <h1>Admin</h1>
  <form action="changepassword" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <label>Roll no</label><input type="number" name="registernumber" class="form-control"/><br>
    <button type="submit"  class="btn btn-blue">Change password</button>
  </form>
  <p>The new password will be <em>cuicuser</em></p>
</div>

app/views/admin/enable_edit.html.erb
<div class="well col-lg-6">
  <h1>Admin</h1>
  <form action="edit_enable" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <label>Roll no</label><input type="number" name="registerno" class="form-control"/><br>
    <button type="submit"  class="btn btn-blue">Enable edit</button>
  </form>
</div>

app/views/admin/excelsheet.html.erb
<div class="well col-lg-6">
  <h1>Admin</h1>
  <form action="userexcel" method="post" enctype="multipart/form-data">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <%= file_field_tag :file %>
    <button type="submit"  class="btn btn-blue">Import excel</button>
  </form>
</div>

app/views/admin/getresults.html.erb
<div class="well">
  <%@users.each do |college_profile|%>
    <p> 
    <%=college_profile.id%>      <%=college_profile.college_profile.degree%>
    <%college_profile.academic_detail.each do |acad|%>
      <%=acad.course%>
    <%end%>
    </p>
  <br>
<%end%>

app/views/admin/index.html.erb
<div class="well col-lg-12">
  <center>  <h1>Admin Panel</h1></center>
  <div class="col-lg-4">
    <h4>User changes</h4>  
    <ul>
      <li>  <%=link_to "Add user(Range)",multi_user_path%></li>
      <li>  <%=link_to "Add user(Single)",single_user_path%></li>
      <li>  <%=link_to "Add user(Excelsheet)",excel_user_path%></li>
      <li><%=link_to "Enable edit",enable_edit_path%>
      <li><%=link_to "Change password",changepassword_path%>

  </ul>
</div>
<div class="col-lg-4">
  <h4>Admin activities</h4>
  <ul>
    <li> <%=link_to "Students sheet","/excelsheet"%></li>
    <li> <%=link_to "Work status",workstatuses_path%></li>
    <li> <%=link_to "Companies",companies_path%></li>
    <li> <%=link_to "Notifications",notifications_path%></li>
    <li> <%=link_to "Courses",courses_path%></li>

  </ul>
</div>
<div class="col-lg-4">
  <ul>
  </ul>
</div>
</div>

app/views/admin/querybuild.html.erb
<div class="well">
<form action="getresults" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
  <input type="text" name="cgpa"/>
  <input type="submit"/>
</form>
</div>

app/views/admin/rollno.html.erb
<div class="well col-lg-6">
  <h1>Admin</h1>
  <form action="createuser" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <label>From</label><input type="number" name="start_number" class="form-control"/><br>
    <label>To</label><input type="number" name="end_number" class="form-control"/><br>
    <button type="submit"  class="btn btn-blue">Create users</button>
  </form>
</div>

app/views/admin/singleuser.html.erb
<div class="well col-lg-6">
  <h1>Admin</h1>
  <form action="singleuser" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <label>Roll no</label><input type="number" name="start_number" class="form-control"/><br>
    <button type="submit"  class="btn btn-blue">Create users</button>
  </form>
  <p>The new password will be <em>cuicuser</em></p>

</div>