config/routes.rb
Rails.application.routes.draw do
  resources :courses

  resources :notifications

  resources :workstatuses

  get 'admin'=>'admin#index'
  get 'admin/query'=>"admin#querybuild"
  post 'admin/getresults'=>"admin#getresults"
  get 'admin/createuser'=>"admin#rollno",:as=>"multi_user"
  post 'admin/createuser'
  get 'admin/excelsheet'=>"admin#excelsheet",:as=>"excel_user"
  post 'admin/userexcel'
  get 'college_profile/branch/:degree'=>"college_profiles#getdegree"
  get 'feedback'=>"home#feedback"
  get 'excelsheet'=>"college_profiles#excel_dump"
  post 'feedback/send'=>"home#send_feedback",:as=>"send_feedback"
  get 'admin/singleuser'=>"admin#singleuser",:as=>"single_user"
  post 'admin/singleuser'=>"admin#loneuser"
  get 'admin/changepassword'=>"admin#change_pass",:as=>"changepassword"
  post 'admin/changepassword'=>'admin#password',:as=>'password_path'
  get 'admin/edit_enable'=>"admin#enable_edit",:as=>"enable_edit"
  post 'admin/edit_enable'=>"admin#enable_edit_action",:as=>"enable"
  get 'myresume'=>"home#print",:as=>"myresume"
  get 'barcode/:filename.:extension'=>"application#barcode",:as=>"barcode"

  resources :companies

  resources :projects

  resources :extra_activities

  resources :semester_marks

  resources :academic_details

  resources :personal_profiles
  resources :college_profiles
  root 'home#index'
  get 'resume'=>"home#resume",:as=>"resume"
  get 'resume/submit'=>"home#submit",:as=>"submit_resume"
  get 'faq'=>"home#faq",:as=>"faq"
  get 'data/user/pic/:id/:filename.:extension'=>"application#download"
  get 'excelsheet/:filename.:extension'=>"application#exceldownload"
  get 'resume/complete'=>"home#complete",:as=>"complete"
  devise_for :users,:controllers=>{registrations:"registrations"},path_names: { sign_up: ''  }

end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  before_filter :authority_check,only: [:new,:edit,:update,:create,:destroy]
  before_filter :sign_in_check
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_notification
    @notification = Notification.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notification_params
    params.require(:notification).permit(:title, :message)
  end
  def sign_in_check
    if not user_signed_in? 
      redirect_to root_path
    end
  end
  def authority_check
    if  not current_user.has_role? "admin"
      redirect_to root_path
    end

  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<div class="well">
<p id="notice"><%= notice %></p>

<h1>Listing Notifications</h1>
<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.title %></td>
        <td><%= notification.message %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>
<%= link_to 'New Notification', new_notification_path %>
</div>

app/views/notifications/new.html.erb
<div class="well">
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>
</div>

app/views/notifications/show.html.erb
<div class="well">
<p>
  <strong>Title:</strong>
  <%= @notification.title %>
</p>
<p>
  <strong>Message:</strong>
  <%= @notification.message %>
</p>
<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>
</div>