config/routes.rb
Rails.application.routes.draw do
  resources :courses

  resources :notifications

  resources :workstatuses

  get 'admin'=>'admin#index'
  get 'admin/query'=>"admin#querybuild"
  post 'admin/getresults'=>"admin#getresults"
  get 'admin/createuser'=>"admin#rollno",:as=>"multi_user"
  post 'admin/createuser'
  get 'admin/excelsheet'=>"admin#excelsheet",:as=>"excel_user"
  post 'admin/userexcel'
  get 'college_profile/branch/:degree'=>"college_profiles#getdegree"
  get 'feedback'=>"home#feedback"
  get 'excelsheet'=>"college_profiles#excel_dump"
  post 'feedback/send'=>"home#send_feedback",:as=>"send_feedback"
  get 'admin/singleuser'=>"admin#singleuser",:as=>"single_user"
  post 'admin/singleuser'=>"admin#loneuser"
  get 'admin/changepassword'=>"admin#change_pass",:as=>"changepassword"
  post 'admin/changepassword'=>'admin#password',:as=>'password_path'
  get 'admin/edit_enable'=>"admin#enable_edit",:as=>"enable_edit"
  post 'admin/edit_enable'=>"admin#enable_edit_action",:as=>"enable"
  get 'myresume'=>"home#print",:as=>"myresume"
  get 'barcode/:filename.:extension'=>"application#barcode",:as=>"barcode"

  resources :companies

  resources :projects

  resources :extra_activities

  resources :semester_marks

  resources :academic_details

  resources :personal_profiles
  resources :college_profiles
  root 'home#index'
  get 'resume'=>"home#resume",:as=>"resume"
  get 'resume/submit'=>"home#submit",:as=>"submit_resume"
  get 'faq'=>"home#faq",:as=>"faq"
  get 'data/user/pic/:id/:filename.:extension'=>"application#download"
  get 'excelsheet/:filename.:extension'=>"application#exceldownload"
  get 'resume/complete'=>"home#complete",:as=>"complete"
  devise_for :users,:controllers=>{registrations:"registrations"},path_names: { sign_up: ''  }

end

app/helpers/home_helper.rb
module HomeHelper
  def prev_month_link
    ->(param, date_range) { link_to(raw("&laquo;"), {param => date_range.first - 1.day},:class=>"cal-link") }
  end
  def next_month_link
    ->(param, date_range) { link_to(raw("&raquo;"), {param => date_range.last + 1.day})}
  end
  def splitter(string)
    return string.split(",")
  end
  def redder(value)
    if value.blank?  || value.nil? 
      "<p class='danger'>Nil</p>".html_safe
    elsif value==0.0 || value==0 || value=="0.0" || value=="0"
      "<p>Not applicable to me</p>".html_safe
    else
      "#{h value}".html_safe 
    end
  end
end

app/views/home/_feedback.html.erb
<div class="modal fade" id="feedbackModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Feedback</h4>
      </div> 
      <div class="modal-body">
        <form method="post" action="<%=send_feedback_path%>">
          <fieldset>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
            <div class="form-group">
              <label>From</label> 
              <%if user_signed_in?%>
                <input type="text" value="<%=current_user.email%>" name="from" readonly=true class="form-control" required="true"/>
              <%else%>
                <input type="text" value="" name="from" class="form-control" required="true"/>
             <%end%>

            </div>
            <div class="form-group">
              <label>To</label><input type="text" value="webmaster_cuic@gmail.com" readonly="true" class="form-control" required="true" />
            </div>
            <div class="form-group">
              <label>Roll no</label>
              <%if user_signed_in?%>
                <input type="text" name="registerno" value="<%=current_user.registerno%>" class="form-control" required="true" readonly="true"/>
              <%else%>
                <input type="text" name="registerno" class="form-control" required="true"/>

              <%end%>
            </div>

            <div class="form-group">
              <label>Subject</label>
              <input type="text" name="subject" class="form-control" required="true"/>
            </div>

            <div class="form-group">
              <label>Message</label>
              <textarea name="message" class="form-control" required="true"></textarea>
            </div>

            <input type="submit" value="Send feedback" class="btn btn-success"/>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/home/_submit.html.erb
<div class="modal fade" id="instructionmodal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <center><h4 class="modal-title">Read before proceeding</h4></center>
      </div>
      <div class="modal-body">
        <ul>
          <li><strong>You can check your entire data in here.If any of the fields are marked as nil and in red please check it in the relevant section.</strong></li>
          <li><strong>By entering zero in any field you indicate that the consent field is not applicable to you.</strong></li>
          <li><strong>Leaving any field empty will be considered as incomplete profile and henceforth will not be considered.</strong></li>
          <li><strong>You can save only once.After which edit will be disabled again</strong></p>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<center><h1>Profile</h1></center>
<%if current_user.can_edit?%>
  <%=link_to complete_path,:class=>"btn btn-primary pull-right" do%> Submit<%end%>
<%else%>
  <center>  <p class="message">This profile has already been submitted</p></center>
<%end%>
<br>
<br>
<br>
<div class="well col-lg-6">
  <center><h3>Personal Profile</h3></center>
  <table class="table">
    <tr>
      <td>Gender</td>
      <td><%=redder @user.personal_profile.gender%></td>
    </tr>
    <tr>
      <td>Dob</td>
      <td><%=redder @user.personal_profile.dob%></td>
    </tr>
    <tr>
      <td>Age</td>
      <td><%=redder @user.personal_profile.age%></td>
    </tr>
    <tr>
      <td>Height</td>
      <td><%=redder @user.personal_profile.height%></td>
    </tr>
    <tr>
      <td>Weight</td>
      <td><%=redder @user.personal_profile.weight%></td>
    </tr>
    <tr>
      <td>Weight</td>
      <td><%=redder @user.personal_profile.weight%></td>
    </tr>
    <tr>
      <td>Nationality and Mother tongue</td>
      <td><%=redder @user.personal_profile.nationality%>/<%=redder @user.personal_profile.mother_tongue%></td>
    </tr>
    <tr>
      <td>Father/Guardian's Name and Occupation</td>
      <td><%=redder @user.personal_profile.guardian_name%><%=redder @user.personal_profile.guardian_occupation%></td>
    </tr>
    <tr>
      <td>Languages you can speak</td>
      <td><%=redder @user.personal_profile.language_speak%></td>
    </tr>
    <tr>
      <td>Languages you can write</td>
      <td><%=redder @user.personal_profile.language_write%></td>
    </tr>
    <tr>
      <td>Languages you can read</td>
      <td><%=redder @user.personal_profile.language_read%></td>
    </tr>
  </table>
</div>
<div class="well col-lg-6">
  <center> <h3>College Profile</h3></center>
  <table class="table">
    <tr>
      <td>DEGREE</td>
      <td><%=redder @user.college_profile.degree%></td>
    </tr>
    <tr>
      <td>Branch</td>
      <td><%=@branch%></td>
    </tr>
    <tr>
      <td>College</td>
      <td><%=redder @user.college_profile.college%></td>
    </tr>
    <tr>
      <td>Level</td>
      <td><%=redder @user.college_profile.level%></td>
    </tr>
    <tr>
      <td>CGPA</td>
      <td><%=redder @user.college_profile.cgpa%></td>
    </tr>
    <tr>
      <td>Current</td>
      <td><%=redder @user.college_profile.current%></td>
    </tr>
    <tr>
      <td>History</td>
      <td><%=redder @user.college_profile.history%></td>
    </tr>

  </table>
</div>
<div class="col-lg-12">
  <center><h3>Academic Profile</h3></center>
  <div class="col-lg-6">
    <center>  <h4>SSLC</h4></center>
    <table class="table">
      <tr>
        <td><strong>Mark</strong></td>
        <td><%=redder @user.academic_detail.sslc_mark%></td>
      </tr>
      <tr>
        <td><strong>Year</strong></td>
        <td><%=redder @user.academic_detail.sslc_year%></td>
      </tr>
      <tr>
        <td><strong>Institute</strong></td>

        <td><%=redder @user.academic_detail.sslc_institute%></td>
      </tr>
      <tr>
        <td><strong>Authority</strong></td>

        <td><%=redder @user.academic_detail.sslc_authority%></td>
      </tr>
    </table>
  </div>
  <div class="col-lg-6">
    <center>  <h4>HSC</h4></center>
    <table class="table">
      <tr>
        <td><strong>Mark</strong></td>
        <td><%=redder @user.academic_detail.hsc_mark%></td>
      </tr>
      <tr>
        <td><strong>Year</strong></td>
        <td><%=redder @user.academic_detail.hsc_year%></td>
      </tr>
      <tr>
        <td><strong>Institute</strong></td>
        <td><%=redder @user.academic_detail.hsc_institute%></td>
      </tr>
      <tr>
        <td><strong>Authority</strong></td>
        <td><%=redder @user.academic_detail.hsc_authority%></td>
      </tr>
    </table>
  </div>
</div>
<div class="col-lg-12">
  <div class="col-lg-6">
    <center>  <h4>UG</h4></center>
    <table class="table">
      <tr>
        <td><strong>Mark</strong></td>
        <td><%=redder( @user.academic_detail.ug_mark.to_s) %></td>
      </tr>
      <tr>
        <td><strong>Year</strong></td>
        <td><%=redder(@user.academic_detail.ug_year.to_s)%></td>
      </tr>
      <tr>
        <td><strong>Institute</strong></td>
        <td><%=redder(@user.academic_detail.ug_institute.to_s)%></td>
      </tr>
      <tr>
        <td><strong>Authority</strong></td>
        <td><%=redder( @user.academic_detail.ug_authority.to_s)%></td>
      </tr>

    </table>
  </div>
  <div class="col-lg-6">
    <center>  <h4>PG</h4></center>
    <table class="table">
      <tr>
        <td><strong>Mark</strong></td>
        <td><%=redder @user.academic_detail.pg_mark%></td>
      </tr>
      <tr>
        <td><strong>Year</strong></td>
        <td><%=redder @user.academic_detail.pg_year%></td>
      </tr>
      <tr>
        <td><strong>Institute</strong></td>
        <td><%=redder @user.academic_detail.pg_institute%></td>
      </tr>
      <tr>
        <td><strong>Authority</strong></td>
        <td><%=redder @user.academic_detail.pg_authority%></td>
      </tr>
    </table>
  </div>
  <div>
  </div>
  <div class="well col-lg-12">
    <center><h3>Semester Marks</h3></center>
    <table class="table">
    <%@user.semester_mark.each do |sem_mark|%>
      <tr>
        <td><%=redder sem_mark.semester%></td>
        <td><%=redder sem_mark.gpa%></td>
        <td> <%=redder sem_mark.pass_year%></td>
      </tr>
    <%end%>
  </table>
  </div>
  <div class="col-lg-12">
    <center><h3>Extra Activities and others <%if @user.extra_activity.nil?%> <p class='danger'>Nil</p><%end%> </h3></center>
    <table class="table">
      <tr>
        <td>Area of interest</td>
        <td><%= redder @user.extra_activity.area_of_interest %></td>
      </tr>
      <tr>
        <td>Extra curricular</td>
        <td><%= redder @user.extra_activity.extra_curricular %></td>
      </tr>
      <tr>
        <td>Hobby</td>
        <td><%= redder @user.extra_activity.hobby %></td>
      </tr>
      <tr>
        <td>Electives</td>
        <td><%= redder @user.extra_activity.electives %></td>
      </tr>
      <tr>
        <td>Responsibilty</td>
        <td><%= redder @user.extra_activity.responsibilty %></td>
      </tr>
    </table>
  </div>
  <div class="well col-lg-12">
    <center><h3>Projects <%if @user.project.nil?%> <p class='danger'>Nil</p><%end%></h3></center>
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Technology</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
      <%@user.project.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.desc %></td>
          <td><%= project.technology %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>
  <%if current_user.can_edit?%>
    <%=link_to complete_path,:class=>"btn btn-primary pull-right" do%> Submit<%end%>
  <%end%>

app/views/home/faq.html.erb
<div class="well col-lg-12">
  <h1><center><i class="mdi-action-question-answer"></i> FAQ</center></h1>
  <div id="faq">
    <h3>Why am I redirected to the account page?</h3>
    <div> <p>You haven't added your email id or phone number.Make sure these are correct and without typographical errors</p></div>
    <h3>What is the dress code?</h3>
    <div><p><b>Boys</b> Formal Shirts and Pants with Shoes.<br> <b>Girls</b> Suitable attire<br>Jeans strictly not allowed.ID card is a must<p></div>
    <h3>What are the things I should bring to an interview</h3>
    <div><p>
      <ul>
        <li>    2-3 hard copies of your resume</li>
        <li> A soft copy of your resume in PDF format on a usb drive</li>
        <li>Passport size photos-2</li>
      </ul>
    </p></div>
    <h3>I am having an arrear.Can I attend the companies visiting the campus?</h3>
    <div><p>No you can't appear if you have an arrear and the visting campus has asked for only for students with no arrears</p></div>
    <h3>I hava applied for revaluation.Does it means that I can attend?</h3>
    <div><p>No you can't appear even though you have applied for revaluation and the visting campus has asked for only for students with no arrears</p></div>
    <h3>What does history of arrears mean?</h3>
    <div><p>A student is said to have history of arrears if in any of his/her previous semesters the student has got an arrear.</p></div>
    <h3>What does current arrears mean?</h3>
    <div><p>The number of arrears you currently hold in this semester</p></div> 
  </div>
</div>

app/views/home/feedback.html.erb
<div class="well col-lg-12">
  <h4 class="modal-title">Feedback</h4>
  <form method="post" action="<%=send_feedback_path%>">
    <fieldset>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
      <div class="form-group">
        <label>From</label> 
        <%if user_signed_in?%>
          <input type="text" value="<%=current_user.email%>" name="from" readonly=true class="form-control" required="true"/>
        <%else%>
          <input type="text" value="" name="from" class="form-control" required="true"/>
        <%end%>

      </div>
      <div class="form-group">
        <label>To</label><input type="text" value="webmaster_cuic@gmail.com" readonly="true" class="form-control" required="true" />
      </div>
      <div class="form-group">
        <label>Roll no</label>
        <%if user_signed_in?%>
          <input type="text" name="registerno" value="<%=current_user.registerno%>" class="form-control" required="true" readonly="true"/>
        <%else%>
          <input type="text" name="registerno" class="form-control" required="true"/>

        <%end%>
      </div>

      <div class="form-group">
        <label>Subject</label>
        <input type="text" name="subject" class="form-control" required="true"/>
      </div>

      <div class="form-group">
        <label>Message</label>
        <textarea name="message" class="form-control" required="true"></textarea>
      </div>

      <input type="submit" value="Send feedback" class="btn btn-success"/>
    </fieldset>
  </form>
</div>

app/views/home/feedback.js.erb
$("#feedback").html("<%=escape_javascript(render(:partial=>"feedback"))%>");
$("#feedbackModal").modal('show');

app/views/home/footer.pdf.erb
<div class="row">
<center>    <img src="<%=barcode_url(current_user.registerno,"png")%>"> </center>     <center><%=current_user.registerno%></center>
</div>
    </div>
    </body>
    </html>

app/views/home/index.html.erb
<div class="well col-lg-12">
  <h1><center><i class="mdi-action-home"></i> HOME</center></h1>
  <div class="col-lg-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="mdi-social-notifications-on"></i> News ticker</h3>
      </div>
      <div class="panel-body">
        <div class="ticker1">
          <div class="innerWrap">
            <%@notifications.each do |notification|%>
              <div class="list">                <%=notification.title%>-<%=notification.message%>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"><i class="mdi-action-event"></i> Placement Calendar</h3>
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <%= month_calendar previous_link: prev_month_link,next_link:next_month_link,table:{class:'table table-bordered'},events: @companies do |date, meetings| %>
          <%= date.strftime("%d") %>
          <% meetings.each do |meeting| %>
            <div>
              <%=link_to meeting do%> <%= meeting.name %> <%end%>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/home/print.html.erb
<div class="well">
</div>

app/views/home/print.pdf.erb
<div class="row">
<center>
<p class="title"><%=current_user.name%> </p>
</center>
<div class="pull-left">
<p><em><%=@college_profile.degree%> <%=@dept%>,<br>College of Engineering,Guindy</em></p>
</div>
<div class="pull-right">
<%=current_user.phone%><br>
<%=current_user.email%>
</div>
</div>
<div style="background-color: black; height: 2px;">
</div>
<br>
<p class="subtitle"><strong>Academic details : </strong></p>
<table class="table table-bordered">
<tr>
<td><strong>Qualification</strong></td>
<td> <strong>Institution</strong></td>
<td><strong>Examination Authority</strong></td>
<td><strong>Year of passing</strong></td>
<td><strong>Score</strong></td>
</tr>
<tr>
        <td>SSLC</td>
        <td><%= @academic_details.sslc_mark %></td>
        <td><%= @academic_details.sslc_institute %></td>
        <td><%= @academic_details.sslc_authority %></td>
        <td><%= @academic_details.sslc_year %></td>
      </tr>
      <tr>
        <td>HSC</td>
        <td><%= @academic_details.hsc_mark %></td>
        <td><%= @academic_details.hsc_institute %></td>
        <td><%= @academic_details.hsc_authority %></td>
        <td><%= @academic_details.hsc_year %></td>
      </tr>
      <tr>
        <td>UG</td>
        <td><%= @academic_details.ug_mark %></td>
        <td><%= @academic_details.ug_institute %></td>
        <td><%= @academic_details.ug_authority %></td>
        <td><%= @academic_details.ug_year %></td>
      </tr>
      <tr>
        <td>PG</td>
        <td><%= @academic_details.pg_mark %></td>
        <td><%= @academic_details.pg_institute %></td>
        <td><%= @academic_details.pg_authority %></td>
        <td><%= @academic_details.pg_year %></td>
        </tr>
<tr>
<td><%=@college_profile.degree%> <%=@dept%></td>
<td><%=@college_profile.college%></td>
<td>Anna University,Chennai</td>
<td>Pursuing</td>
<td><%=@college_profile.cgpa%></td>
</table>
<p class="subtitle"><strong>Projects: </strong> </p>
<%@projects.each do |project|%>
  <strong> <h4><%=project.title%></h4></strong>
  <strong>Description: </strong> <%=project.desc%><br>
  <strong>Technologies used: </strong> <%=project.technology%>
<%end%>
<br>
<br>
<br>
<%if not @extra_activities.nil?%>
  <p class="subtitle"><strong>Areas of interest</strong></p>
  <ul>
  <%splitter(@extra_activities.area_of_interest).each do |area|%>
    <li><%=area%></li>
  <%end%>
  </ul>
  <br>
  <p class="subtitle"><strong>Responsibility</strong></p>
  <ul>
  <%splitter(@extra_activities.responsibilty).each do |resp|%>
    <li><%=resp%></li>
  <%end%>
  </ul>
  <br>
  <p class="subtitle"><strong>Extra Curricular</strong></p>
  <ul>
  <%splitter(@extra_activities.extra_curricular).each do |extras|%>
    <li><%=extras%></li>
  <%end%>
  </ul>
  <br>
  <p class="subtitle"><strong>Hobbies</strong></p>
  <ul>
  <%splitter(@extra_activities.hobby).each do |hob|%> 
    <li><%=hob%></li>
  <%end%>
  </ul>
<%end%>
<strong>Declaration</strong>
<p>I hereby declare that the above furnished information is true to the best of my knowledge </p>

<br><br>
<div class="pull-right">
<strong>(<%=current_user.name%>)</strong>
</div>
</div>
</div>

app/views/home/resume.html.erb
<div class="col-lg-3">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"><i class="mdi-maps-my-location"></i> Links</h3>
    </div>
    <div class="panel-body">
      <ul class="nav nav-pills nav-stacked">
        <li> <%=link_to personal_profiles_path,:onclick=>"gaTrack('/personal_profile','Personal Profile')",:remote=>true do%><i class="mdi-social-person-outline"></i> Personal Profile<%end%> </li>
        <li><%=link_to college_profiles_path,:onclick=>"gaTrack('/college_profiles','College Profile')",:remote=>true do%><i class="mdi-maps-local-library"></i> College Profile<%end%></li>
        <li><%=link_to academic_details_path,:onclick=>"gaTrack('/academic_details','Academic Details')",:remote=>true do%><i class="mdi-social-school"></i> Academic details<%end%></li>
        <li><%=link_to semester_marks_path,:onclick=>"gaTrack('/semester_marks','Semester Marks')",:remote=>true do%><i class="mdi-action-view-list"></i> Semester Marks<%end%></li>
        <li><%=link_to extra_activities_path,:onclick=>"gaTrack('/extra_activities','Extra Activities')",:remote=>true do%><i class="mdi-image-filter-vintage"></i> Extra Curricular and others<%end%></li>
        <li><%=link_to projects_path,:onclick=>"gaTrack('/projects','Projects')",:remote=>true do%><i class="mdi-image-landscape"></i> Project<%end%></li>
        <li><%=link_to submit_resume_path,:onclick=>"gaTrack('/projects','Projects')",:remote=>true ,:class=>"submit-resume" do%><i class="mdi-maps-beenhere"></i> Submit my resume<%end%></li>
      </ul>
    </div>
  </div>
</div>
<div class="well col-lg-9" id="ajaxarea">
  <div id="ajaxloader"></div>
  <p class="headline">Instructions </p>
  <ol>
    <li>Each section will have separate list of fields.You can save each section separately.All sections must completed.</li>
    <li>Have your details ready while entering to avoid delay.</li>
    <li>In academic detail section please choose only what is applicable</li>
    <li>In semester marks section
    <ul>
      <li>PG students enter your marks only for PG semesters.Your UG marks are not needed</li>
      <li>UG students enter your marks from semester 1 to the latest semester</li>
    </ul>
    </li>
    <li>For electives in Extra curricular activity section,If you have more than one use commas to separate them</li>
    <li>In projects section,you are allowed to include any number of projects.But only your first three will be considered</li>
    <li><strong>You can check your entire resume using Submit my resume link in the left hand side.If any of the fields are marked as nil and in red please check it in the relevant section.</strong></li>
    <li><strong>By entering zero in any field you indicate that the consent field is not applicable to you.</strong></li>
    <li><strong>Leaving any field empty will be considered as incomplete profile and henceforth will not be considered.</strong></li>
    <li><strong>You can save only once.After which edit will be disabled again</strong></p>
  </ol>
</div>

app/views/home/submit.js.erb
$("#ajaxarea").html("<%= escape_javascript(render(:partial=>"submit"))%>")
$('#instructionmodal').modal('show')