config/routes.rb
Rails.application.routes.draw do
  resources :courses

  resources :notifications

  resources :workstatuses

  get 'admin'=>'admin#index'
  get 'admin/query'=>"admin#querybuild"
  post 'admin/getresults'=>"admin#getresults"
  get 'admin/createuser'=>"admin#rollno",:as=>"multi_user"
  post 'admin/createuser'
  get 'admin/excelsheet'=>"admin#excelsheet",:as=>"excel_user"
  post 'admin/userexcel'
  get 'college_profile/branch/:degree'=>"college_profiles#getdegree"
  get 'feedback'=>"home#feedback"
  get 'excelsheet'=>"college_profiles#excel_dump"
  post 'feedback/send'=>"home#send_feedback",:as=>"send_feedback"
  get 'admin/singleuser'=>"admin#singleuser",:as=>"single_user"
  post 'admin/singleuser'=>"admin#loneuser"
  get 'admin/changepassword'=>"admin#change_pass",:as=>"changepassword"
  post 'admin/changepassword'=>'admin#password',:as=>'password_path'
  get 'admin/edit_enable'=>"admin#enable_edit",:as=>"enable_edit"
  post 'admin/edit_enable'=>"admin#enable_edit_action",:as=>"enable"
  get 'myresume'=>"home#print",:as=>"myresume"
  get 'barcode/:filename.:extension'=>"application#barcode",:as=>"barcode"

  resources :companies

  resources :projects

  resources :extra_activities

  resources :semester_marks

  resources :academic_details

  resources :personal_profiles
  resources :college_profiles
  root 'home#index'
  get 'resume'=>"home#resume",:as=>"resume"
  get 'resume/submit'=>"home#submit",:as=>"submit_resume"
  get 'faq'=>"home#faq",:as=>"faq"
  get 'data/user/pic/:id/:filename.:extension'=>"application#download"
  get 'excelsheet/:filename.:extension'=>"application#exceldownload"
  get 'resume/complete'=>"home#complete",:as=>"complete"
  devise_for :users,:controllers=>{registrations:"registrations"},path_names: { sign_up: ''  }

end

app/models/personal_profile.rb
class PersonalProfile < ActiveRecord::Base
  validates_presence_of :gender
  validates_presence_of :dob
  validates :dob,:date=>true
  validates_presence_of :age
  validates_numericality_of :age,:on=>[:create,:update]
  validates_presence_of :height
  validates_numericality_of :height,:on=>[:create,:update]
  validates_presence_of :weight
  validates_numericality_of :weight,:on=>[:create,:update]
  validates_presence_of :guardian_name
  validates_presence_of :guardian_occupation
  validates_presence_of :nationality
  validates_presence_of :mother_tongue
  validates_presence_of :language_speak
  validates_presence_of :language_write
  validates_presence_of :language_read
  validates_presence_of :social_status
end

app/controllers/personal_profiles_controller.rb
class PersonalProfilesController < ApplicationController
  before_action :set_personal_profile, only: [:show, :edit, :update, :destroy]
  before_filter :sign_in_check 
  before_filter :edit_check,only:[:edit,:update,:destroy,:new]
  respond_to :js,:html
  # GET /personal_profiles
  # GET /personal_profiles.json
  def index
    @personal_profiles =current_user.personal_profile
  end

  # GET /personal_profiles/1
  # GET /personal_profiles/1.json
  def show
  end

  # GET /personal_profiles/new
  def new
    @personal_profile = PersonalProfile.new
  end

  # GET /personal_profiles/1/edit
  def edit
  end

  # POST /personal_profiles
  # POST /personal_profiles.json
  def create
    @personal_profile = PersonalProfile.new(personal_profile_params)
    @personal_profile.user_id=current_user.id
    respond_to do |format|
      if @personal_profile.save
        format.html { redirect_to resume_path, notice: 'Personal profile was successfully created.' }
        format.json { render :show, status: :created, location: resume_path }
      else
        format.html { render :new }
        format.json { render json: @personal_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_profiles/1
  # PATCH/PUT /personal_profiles/1.json
  def update
    respond_to do |format|
      if @personal_profile.update(personal_profile_params)
        format.html { redirect_to resume_path, notice: 'Your Personal profile was successfully updated.' }
        format.json { render :show, status: :ok, location: resume_path }
      else
        format.html { render :edit }
        format.json { render json: @personal_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_profiles/1
  # DELETE /personal_profiles/1.json
  def destroy
    @personal_profile.destroy
    respond_to do |format|
      format.html { redirect_to resume_path, notice: 'Personal profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_personal_profile
    @personal_profile = current_user.personal_profile
    if not @personal_profile.user_id==current_user.id
      redirect_to root_path
    end

  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def personal_profile_params
    params.require(:personal_profile).permit(:gender, :dob, :age, :height, :weight, :guardian_name, :guardian_occupation, :nationality, :mother_tongue,:user_id,:current_address,:permanent_address,:communicate,:language_speak,:language_read,:language_write,:social_status)
  end
  def sign_in_check
    if not user_signed_in?
      redirect_to new_user_session_path
    end
  end
  def edit_check
    if not current_user.can_edit?
      respond_to do |format|
        @error_message="Add or Edit disabled"
        format.js{render 'layouts/edit_disable',notice:'Edit disabled'}
        format.html{redirect_to resume_path,alert:'Delete disabled'}
      end
    end
  end
end

app/helpers/personal_profiles_helper.rb
module PersonalProfilesHelper
end

app/views/personal_profiles/_edit.html.erb
<center><h1><i class="mdi-social-person-outline"></i> Editing Personal Profile</h1></center>
<%= render 'form' %>

app/views/personal_profiles/_form.html.erb
<%= form_for(@personal_profile,:class=>"form-horizontal") do |f| %>
  <%= link_to :back  ,:class=>"btn btn-danger" do%>
    <i class="mdi-hardware-keyboard-arrow-left"></i> Back
  <%end%>

  <button type="submit" class="btn btn-primary pull-right"><i class="mdi-content-save"></i>Save</button>
  <% if @personal_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personal_profile.errors.count, "error") %> prohibited this personal_profile from being saved:</h2>
      <ul>
        <% @personal_profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :gender %><br>
    <div class="radio radio-primary">
      <label>
        <%= f.radio_button :gender,:male,:class=>"form-control",:required=>true %>  Male
        <span class="circle"></span>
        <span class="check"></span>
      </label>
      <label>
        <%= f.radio_button :gender,:female,:class=>"form-control",:required=>true %> Female
        <span class="circle"></span>
        <span class="check"></span>

      </label>
    </div>

  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-6">

        <label for="dob">Date of Birth</label><br>
        <%= f.text_field :dob ,:class=>"form-control" ,:required=>true,:id=>"date" %>
      </div>
      <div class="col-md-6">
        <%= f.label :age %><br>
        <%= f.text_field :age ,:class=>"form-control" ,:required=>true %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-6">
        <%= f.label :height %><br>
        <%= f.text_field :height ,:class=>"form-control" ,:required=>true %>
      </div>
      <div class="col-md-6">
        <%= f.label :weight %><br>
        <%= f.text_field :weight ,:class=>"form-control" ,:required=>true %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <label for="guardian_name">Father/Guardian's name</label>
    <%= f.text_area :guardian_name ,:class=>"form-control" ,:required=>true %>
  </div>
  <div class="form-group">
    <label for="guardian_occupation">Father/Guardian's occupation</label>

    <%= f.text_area :guardian_occupation ,:class=>"form-control" ,:required=>true %>
  </div>
  <div class="form-group">
    <%= f.label :nationality%><br>
    <%= f.text_field :nationality ,:class=>"form-control" ,:required=>true  %>
  </div>
  <div class="form-group">
    <%= f.label :mother_tongue %><br>
    <%= f.text_field :mother_tongue ,:class=>"form-control" ,:required=>true %>
  </div>
  <div class="form-group">
    <%= f.label :current_address %><br>
    <%= f.text_area :current_address ,:class=>"form-control" ,:required=>true %>
  </div>
  <div class="form-group">
    <%= f.label :permanent_address %><br>
    <%= f.text_area :permanent_address ,:class=>"form-control" ,:required=>true %>
  </div>
  <div class="form-group">
    <%= f.label :communicate %><br>
    <%= f.select :communicate ,options_for_select([["Permanent","permanent"],["Current","current"]]), :class=>"form-control" ,:required=>true %>
  </div>
  <div class="form-group">
    <%= f.label :languages_you_can_speak %><br>
    <%= f.text_area :language_speak ,:class=>"form-control" ,:required=>true %>
  </div>
  <div class="form-group">
    <%= f.label :languages_you_can_read %><br>
    <%= f.text_area :language_read ,:class=>"form-control" ,:required=>true %>
  </div>
  <div class="form-group">
    <%= f.label :languages_you_can_write%><br>
    <%= f.text_area :language_write ,:class=>"form-control" ,:required=>true %>
  </div>
  <div class="form-group">
    <%= f.label :social_status %><br>
    <%= f.select :social_status ,options_for_select("OC"=>"OC","BC"=>"BC","MBC"=>"MBC","BCM"=>"BCM","SC"=>"SC","SCA"=>"SCA","ST"=>"ST","others"=>"others"),:class=>"form-control" ,:required=>true %>
  </div>
  <div class="form-group">
    <%= f.label :physically_challenged %><br>
    <%= f.select :physically_challenged ,options_for_select("Yes"=>"yes","No"=>"No"),:class=>"form-control" ,:required=>true %>
  </div>


  <%= link_to :back  ,:class=>"btn btn-danger" do%>
    <i class="mdi-hardware-keyboard-arrow-left"></i> Back
  <%end%>
  <button type="submit" class="btn btn-primary pull-right"><i class="mdi-content-save"></i>Save</button>
<% end %>
<script>
</script>

app/views/personal_profiles/_index.html.erb
<h1><center><i class="mdi-social-person-outline"></i>Personal Profile</center></h1>
<%if not @personal_profiles.nil?%>
<%= link_to @personal_profiles, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger pull-right" do%>
<i class="mdi-action-delete"></i> Destroy
<%end%>
<%= link_to edit_personal_profile_path(@personal_profiles),:class=>"btn btn-large btn-success pull-right",:remote=>true do%> 
<i class="mdi-editor-mode-edit"></i> Edit
<%end%>
<%= link_to :back,:class=>"btn btn-large btn-danger" do%> 
<i class="mdi-hardware-keyboard-arrow-left"></i> Back
<%end%>
<br>
<dl class="dl-horizontal">
  <dt>Gender</dt>
  <dd><%= @personal_profiles.gender %></dd>
  <dt>Date of Birth</dt>
  <dd><%=Date.parse(@personal_profiles.dob).strftime("%B %d,%Y")%></dd>
  <dt>Age</dt>
  <dd><%=@personal_profiles.age %></dd>
  <dt>Height</dt>
  <dd><%=@personal_profiles.height %></dd>
  <dt>Weight</dt>
  <dd><%=@personal_profiles.weight %></dd>
  <dt>Father/Guardian name</dt>
  <dd><%=@personal_profiles.guardian_name %></dd>
  <dt>Father/Guardian occupation</dt>
  <dd><%=@personal_profiles.guardian_occupation %></dd>
  <dt>Nationality</dt>
  <dd><%=@personal_profiles.nationality %></dd>
  <dt>Mother tongue</dt>
  <dd><%=@personal_profiles.mother_tongue %></dd>
 <dt>Language you can speak</dt>
 <dd> <%=@personal_profiles.language_speak%></dd>
 <dt>Language you can read</dt>
 <dd><%=@personal_profiles.language_read%> </dd>
 <dt>Language you can write</dt>
 <dd><%=@personal_profiles.language_write%> </dd>
 <dt>Social Status</dt>
 <dd><%=@personal_profiles.social_status%></dd>
</dl>
<%else%>
<center><p class="message"><i class="mdi-alert-warning"></i>  No Personal Profile yet</p></center>
<center>
  <%= link_to new_personal_profile_path,:class=>"btn btn-primary",:remote=>true do %>
  <i class="mdi-content-add"></i> Add
  <%end%>
</center>
<%end%>

app/views/personal_profiles/_new.html.erb
  <center><h1><i class="mdi-social-person-outline"></i> New Personal Profile</h1></center>
<%= render 'form' %>
<script>
$(document).ready(function(){
$('#date').datepicker({
  changeMonth: true,
  changeYear: true,
  yearRange: "-30:+0"

  });
})
</script>

app/views/personal_profiles/edit.html.erb
<div class="well">
<center><h1><i class="mdi-social-person-outline"></i> Editing Personal Profile</h1></center>
<%= render 'form' %>
</div>
<script>
$(document).ready(function(){
pp=$("select#personal_profile_social_status")
pp.val("<%=@personal_profile.social_status%>")
pp=$("select#personal_profile_physically_challenged")
pp.val("<%=@personal_profile.physically_challenged%>")
pp=$("select#personal_profile_communicate")
pp.val("<%=@personal_profile.communicate%>")
});
</script>

app/views/personal_profiles/edit.js.erb
$("#ajaxarea").html("<%= escape_javascript(render(:partial=>"edit"))%>");
pp=$("select#personal_profile_social_status")
pp.val("<%=@personal_profile.social_status%>")
pp=$("select#personal_profile_physically_challenged")
pp.val("<%=@personal_profile.physically_challenged%>")
pp=$("select#personal_profile_communicate")
pp.val("<%=@personal_profile.communicate%>")
$('#date').datepicker({
  changeMonth: true,
  changeYear: true,
  yearRange: "-30:+0",
 dateFormat: 'yy-mm-dd'

});

app/views/personal_profiles/index.html.erb
<div class="well">
<h1><center><i class="mdi-social-person-outline"></i>Personal Profile</center></h1>
<%if not @personal_profiles.nil?%>
<%= link_to @personal_profiles, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger pull-right" do%>
<i class="mdi-action-delete"></i> Destroy
<%end%>
<%= link_to edit_personal_profile_path(@personal_profiles),:class=>"btn btn-large btn-success pull-right" do%> 
<i class="mdi-editor-mode-edit"></i> Edit
<%end%>
<%= link_to :back,:class=>"btn btn-large btn-danger" do%> 
<i class="mdi-hardware-keyboard-arrow-left"></i> Back
<%end%>
<br>
<dl class="dl-horizontal">
  <dt>Gender</dt>
  <dd><%= @personal_profiles.gender %></dd>
  <dt>Dob</dt>
  <dd><%=@personal_profiles.dob %></dd>
  <dt>Age</dt>
  <dd><%=@personal_profiles.age %></dd>
  <dt>Height</dt>
  <dd><%=@personal_profiles.height %></dd>
  <dt>Weight</dt>
  <dd><%=@personal_profiles.weight %></dd>
  <dt>Father/Guardian name</dt>
  <dd><%=@personal_profiles.guardian_name %></dd>
  <dt>Father/Guardian occupation</dt>
  <dd><%=@personal_profiles.guardian_occupation %></dd>
  <dt>Nationality</dt>
  <dd><%=@personal_profiles.nationality %></dd>
  <dt>Mother tongue</dt>
  <dd><%=@personal_profiles.mother_tongue %></dd>
</dl>
<%else%>
<center><p class="message"><i class="mdi-alert-warning"></i>  No Personal Profile yet</p></center>
<center>
  <%= link_to new_personal_profile_path,:class=>"btn btn-primary" do %>
  <i class="mdi-content-add"></i> Add
  <%end%>
</center>
<%end%>
</div>

app/views/personal_profiles/new.html.erb
<div class="well">
  <center><h1><i class="mdi-social-person-outline"></i> New Personal Profile</h1></center>
<%= render 'form' %>
</div>
<script>
$(document).ready(function(){
$('#date').datepicker({
  changeMonth: true,
  changeYear: true,
  yearRange: "-30:+0"

  });
})
</script>

app/views/personal_profiles/new.js.erb
$("#ajaxarea").html("<%= escape_javascript(render(:partial =>"new"))%>");
$('#date').datepicker({
  changeMonth: true,
  changeYear: true,
  yearRange: "-30:+0",
  dateFormat: 'yy-mm-dd'
});

app/views/personal_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gender:</strong>
  <%= @personal_profile.gender %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @personal_profile.dob %>
</p>

<p>
  <strong>Age:</strong>
  <%= @personal_profile.age %>
</p>

<p>
  <strong>Height:</strong>
  <%= @personal_profile.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @personal_profile.weight %>
</p>

<p>
  <strong>Guardian name:</strong>
  <%= @personal_profile.guardian_name %>
</p>

<p>
  <strong>Guardian occupation:</strong>
  <%= @personal_profile.guardian_occupation %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @personal_profile.nationality %>
</p>

<p>
  <strong>Mother tongue:</strong>
  <%= @personal_profile.mother_tongue %>
</p>

<%= link_to 'Edit', edit_personal_profile_path(@personal_profile) %> |
<%= link_to 'Back', personal_profiles_path %>